# Generated by Django 4.0 on 2021-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dagen',
            field=models.DateField(blank=True, default=0.0005263157894736842),
            preserve_default=False,
        ),
    ]
