# Generated by Django 4.0 on 2021-12-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_dagfan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dagfan',
            field=models.CharField(max_length=12),
        ),
    ]
